CREATE TABLE IF NOT EXISTS event (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(60),
	place VARCHAR(60),
	starts_at TIMESTAMP,
	ends_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS attendee (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	full_name  VARCHAR(120),
	email VARCHAR(120),
	event_id INTEGER,
	CONSTRAINT event_fk FOREIGN KEY event_id REFERENCES event(id)
);